name: NConvex
version: "2019.09.02"
date: 2019-09-02
description: |
    A Gap package to perform polyhedral computations

authors:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io/

maintainers:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io/

GAP: ">= 4.6"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2018.02.14"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "Modules"
      version: ">= 0.5"
      url: "https://homalg-project.github.io/homalg_project/Modules/"
    - name: "CddInterface"
      version: ">= 2019.08.28"
      url: "https://homalg-project.github.io/CddInterface"
    - name: "NormalizInterface"
      version: ">= 1.1.0"
      url: "https://gap-packages.github.io/NormalizInterface"

suggested-pkgs:
    - name: "4ti2Interface"
      version: ">= 2018.07.06"
      url: "https://homalg-project.github.io/homalg_project/4ti2Interface/"
    - name: "TopcomInterface"
      version: ">=2019.06.15"
      url: "https://github.com/HereAround/TopcomInterface"

www: https://homalg-project.github.io/NConvex
readme: README.md
packageinfo: https://github.com/homalg-project/NConvex/releases/latest/download/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/NConvex/archive/2019.09.02.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Cone, Fan, Polytope, Polyhedron, ToricVarieties, homalg.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>SG19</span>]   <b class='BibAuthor'>Saleh, K. and Gutsche, S.</b>,
     <i class='BibTitle'>NConvex, A Gap package to perform polyhedral computations,
             Version 2019.09.02</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/NConvex">https://homalg-project.github.io/NConvex</a></span>.
    </p>
    

bibtex: |
    @misc{ NConvex2019.09.02,
      author =           {Saleh, K. and Gutsche, S.},
      title =            {{NConvex}, A Gap package to perform polyhedral computations, {V}ersion 2019.09.02},
      month =            {Sep},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href   {https://homalg-project.github.io/NConvex}  {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{NConvex}}},
      keywords =         {Cone; Fan; Polytope; Polyhedron; ToricVarieties; homalg},
      printedkey =       {SG19}
    }

