name: NConvex
version: "2025.12-02"
license: "GPL-2.0-or-later"
date: 2025-12-24
description: |
    A Gap package to perform polyhedral computations

authors:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io/

maintainers:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh

GAP: ">= 4.13.0"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2025.12.19"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "Modules"
      version: ">= 0.5"
      url: "https://homalg-project.github.io/pkg/Modules"
    - name: "CddInterface"
      version: ">= 2020.06.24"
      url: "https://homalg-project.github.io/CddInterface"
    - name: "NormalizInterface"
      version: ">= 1.1.0"
      url: "https://gap-packages.github.io/NormalizInterface"

suggested-pkgs:
    - name: "4ti2Interface"
      version: ">= 2018.07.06"
      url: "https://homalg-project.github.io/pkg/4ti2Interface"
    - name: "TopcomInterface"
      version: ">=2019.06.15"

www: https://homalg-project.github.io/pkg/NConvex
readme: README.md
packageinfo: https://homalg-project.github.io/NConvex/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/NConvex/releases/download/v2025.12-02/NConvex-2025.12-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/NConvex/releases/download/v2025.12-02/NConvex-2025.12-02.zip

pdf: https://github.com/homalg-project/NConvex/releases/download/v2025.12-02/NConvex-2025.12-02.pdf

abstract: |
    The <span class='pkgname'>NConvex</span> package is a GAP package.   Its aim is to carry out polyhedral constructions and computations,  namely computing properties and attributes of cones, polyhedrons, polytopes and fans.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Cone, Fan, Polytope, Polyhedron, ToricVarieties, homalg.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>SG24</span>]   <b class='BibAuthor'>Saleh, K. and Gutsche, S.</b>,
     <i class='BibTitle'>NConvex, A Gap package to perform polyhedral computations,
             Version 2025.12-02</i>
     (<span class='BibYear'>2-24</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/NConvex">https://homalg-project.github.io/pkg/NConvex</a></span>.
    </p>
    

bibtex: |
    @misc{ NConvex,
      author =           {Saleh, K. and Gutsche, S.},
      title =            {{NConvex},   {A  Gap  package  to  perform  polyhedral
                          computations}, {V}ersion 2025.12\texttt{\symbol{45}}02},
      month =            {5\texttt{\symbol{45}}},
      year =             {2\texttt{\symbol{45}}24},
      note =             {GAP package},
      howpublished =     {\href   {https://homalg-project.github.io/pkg/NConvex}
                          {\texttt{https://homalg\texttt{\symbol{45}}project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{NConvex}}},
      keywords =         {Cone;   Fan;   Polytope;  Polyhedron;  ToricVarieties;
                          homalg},
      printedkey =       {SG24}
    }

